### ISSUE TITLE
Open issues on https://github.com/mhkeller/pulp2 ;)

### ISSUE THREAD

**Issue by nylnook** [ajam/pulp#45]
Hello Michael !
How are you since last year ?

Back to pulp to publish my next comic, and so I'm optimizing pulp for Docpad right now finally.
Once it will be ready, I'll let you know ;)

I see you forked you own repo, so maybe you should open Issues on the new repository ?

two issues until now:
- you should remove Bloomberg  from your source header I suppose
- In pulp-icon.css, the pathe to the font is wrong (need to remove the "/pulp-icon/" sub-directory)

Thanks again for this great comic viewer !

**Comment by mhkeller** [comment]
Hey Camille!

Thanks for these — I'll fix them. Or if you want to issue a pull request feel free. Yep my fork of pulp is the one I'll be maintaining so you can file issues / PRs on that one.

**Comment by nylnook** [comment]
I'll do that ;)
sorry I wasn't clear and mixed everything, can you just check the "issues" checkbox in your fork settings ? Right now, your forked repo has no Issues tab ;p

Thansk ;)

**Comment by mhkeller** [comment]
Ah got it. All done https://github.com/mhkeller/pulp2/issues
